---
system:
  privateKeyPath: "/home/root/certs/private.key"
  certificateFilePath: "/home/root/certs/certificate.pem"
  rootCaPath: "/home/root/certs/AmazonRootCA1.pem"
  rootPath: "/home/root/run"
  thingName: ""
services:
  aws.greengrass.Nucleus-Lite:
    componentType: "NUCLEUS"
    configuration:
      awsRegion: ""
      iotCredEndpoint: ""
      iotDataEndpoint: ""
      iotRoleAlias: ""
      runWithDefault:
        posixUser: "root:root"
      greengrassDataPlanePort: "8443"
      tesCredUrl: "http://127.0.0.1:8080/"
